DROP INDEX IF EXISTS public.virtavesikapea_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.virtavesialue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.virtausnuoli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.viettoviiva_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.vesikuoppa_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.vesikulkuvayla_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.vesikivikko_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.vesikivi_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.vedenpinnankorkeusluku_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.urheilujavirkistysalue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.tulentekopaikka_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.tieviiva_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.tiesymboli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.tienroteksti_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.syvyyspiste_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.syvyyskayransyvyysarvo_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.syvyyskayra_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.suurjannitelinjanpylvas_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.suojelualueenreunaviiva_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.suo_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.soistuma_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.selite_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.sahkolinjansymboli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.sahkolinja_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.rauhoitettukohde_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.rakennusreunaviiva_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.rakennus_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.rakennelma_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.pato_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.paikannimi_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.niitty_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.muuntaja_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.muuavoinalue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.metsamaankasvillisuus_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.matalikko_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.mastonkorkeus_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.masto_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.maatuvavesialue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.maatalousmaa_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.maastokuvionreuna_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.maasto2kuvionreuna_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.maaaineksenottoalue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.luonnonsuojelualue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.luiska_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.lahde_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kunta_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kunnanhallintoraja_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.koski_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.korkeuskiintopiste_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.korkeuskayrankorkeusarvo_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.korkeuskayra_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kolmiopiste_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kivikko_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kivi_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kellotapuli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.karttasymboli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kansallispuisto_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kalliosymboli_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kallioalue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.kaislikko_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.jyrkanne_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.jarvi_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.hautausmaa_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.harvalouhikko_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.autoliikennealue_wkb_geometry_geom_idx;
DROP INDEX IF EXISTS public.allas_wkb_geometry_geom_idx;
ALTER TABLE IF EXISTS ONLY public.virtavesikapea DROP CONSTRAINT IF EXISTS virtavesikapea_pkey;
ALTER TABLE IF EXISTS ONLY public.virtavesialue DROP CONSTRAINT IF EXISTS virtavesialue_pkey;
ALTER TABLE IF EXISTS ONLY public.virtausnuoli DROP CONSTRAINT IF EXISTS virtausnuoli_pkey;
ALTER TABLE IF EXISTS ONLY public.viettoviiva DROP CONSTRAINT IF EXISTS viettoviiva_pkey;
ALTER TABLE IF EXISTS ONLY public.vesikuoppa DROP CONSTRAINT IF EXISTS vesikuoppa_pkey;
ALTER TABLE IF EXISTS ONLY public.vesikulkuvayla DROP CONSTRAINT IF EXISTS vesikulkuvayla_pkey;
ALTER TABLE IF EXISTS ONLY public.vesikivikko DROP CONSTRAINT IF EXISTS vesikivikko_pkey;
ALTER TABLE IF EXISTS ONLY public.vesikivi DROP CONSTRAINT IF EXISTS vesikivi_pkey;
ALTER TABLE IF EXISTS ONLY public.vedenpinnankorkeusluku DROP CONSTRAINT IF EXISTS vedenpinnankorkeusluku_pkey;
ALTER TABLE IF EXISTS ONLY public.urheilujavirkistysalue DROP CONSTRAINT IF EXISTS urheilujavirkistysalue_pkey;
ALTER TABLE IF EXISTS ONLY public.tulentekopaikka DROP CONSTRAINT IF EXISTS tulentekopaikka_pkey;
ALTER TABLE IF EXISTS ONLY public.tieviiva DROP CONSTRAINT IF EXISTS tieviiva_pkey;
ALTER TABLE IF EXISTS ONLY public.tiesymboli DROP CONSTRAINT IF EXISTS tiesymboli_pkey;
ALTER TABLE IF EXISTS ONLY public.tienroteksti DROP CONSTRAINT IF EXISTS tienroteksti_pkey;
ALTER TABLE IF EXISTS ONLY public.syvyyspiste DROP CONSTRAINT IF EXISTS syvyyspiste_pkey;
ALTER TABLE IF EXISTS ONLY public.syvyyskayransyvyysarvo DROP CONSTRAINT IF EXISTS syvyyskayransyvyysarvo_pkey;
ALTER TABLE IF EXISTS ONLY public.syvyyskayra DROP CONSTRAINT IF EXISTS syvyyskayra_pkey;
ALTER TABLE IF EXISTS ONLY public.suurjannitelinjanpylvas DROP CONSTRAINT IF EXISTS suurjannitelinjanpylvas_pkey;
ALTER TABLE IF EXISTS ONLY public.suojelualueenreunaviiva DROP CONSTRAINT IF EXISTS suojelualueenreunaviiva_pkey;
ALTER TABLE IF EXISTS ONLY public.suo DROP CONSTRAINT IF EXISTS suo_pkey;
ALTER TABLE IF EXISTS ONLY public.soistuma DROP CONSTRAINT IF EXISTS soistuma_pkey;
ALTER TABLE IF EXISTS ONLY public.selite DROP CONSTRAINT IF EXISTS selite_pkey;
ALTER TABLE IF EXISTS ONLY public.sahkolinjansymboli DROP CONSTRAINT IF EXISTS sahkolinjansymboli_pkey;
ALTER TABLE IF EXISTS ONLY public.sahkolinja DROP CONSTRAINT IF EXISTS sahkolinja_pkey;
ALTER TABLE IF EXISTS ONLY public.rauhoitettukohde DROP CONSTRAINT IF EXISTS rauhoitettukohde_pkey;
ALTER TABLE IF EXISTS ONLY public.rakennusreunaviiva DROP CONSTRAINT IF EXISTS rakennusreunaviiva_pkey;
ALTER TABLE IF EXISTS ONLY public.rakennus DROP CONSTRAINT IF EXISTS rakennus_pkey;
ALTER TABLE IF EXISTS ONLY public.rakennelma DROP CONSTRAINT IF EXISTS rakennelma_pkey;
ALTER TABLE IF EXISTS ONLY public.pato DROP CONSTRAINT IF EXISTS pato_pkey;
ALTER TABLE IF EXISTS ONLY public.paikannimi DROP CONSTRAINT IF EXISTS paikannimi_pkey;
ALTER TABLE IF EXISTS ONLY public.niitty DROP CONSTRAINT IF EXISTS niitty_pkey;
ALTER TABLE IF EXISTS ONLY public.muuntaja DROP CONSTRAINT IF EXISTS muuntaja_pkey;
ALTER TABLE IF EXISTS ONLY public.muuavoinalue DROP CONSTRAINT IF EXISTS muuavoinalue_pkey;
ALTER TABLE IF EXISTS ONLY public.metsamaankasvillisuus DROP CONSTRAINT IF EXISTS metsamaankasvillisuus_pkey;
ALTER TABLE IF EXISTS ONLY public.matalikko DROP CONSTRAINT IF EXISTS matalikko_pkey;
ALTER TABLE IF EXISTS ONLY public.mastonkorkeus DROP CONSTRAINT IF EXISTS mastonkorkeus_pkey;
ALTER TABLE IF EXISTS ONLY public.masto DROP CONSTRAINT IF EXISTS masto_pkey;
ALTER TABLE IF EXISTS ONLY public.maatuvavesialue DROP CONSTRAINT IF EXISTS maatuvavesialue_pkey;
ALTER TABLE IF EXISTS ONLY public.maatalousmaa DROP CONSTRAINT IF EXISTS maatalousmaa_pkey;
ALTER TABLE IF EXISTS ONLY public.maastokuvionreuna DROP CONSTRAINT IF EXISTS maastokuvionreuna_pkey;
ALTER TABLE IF EXISTS ONLY public.maasto2kuvionreuna DROP CONSTRAINT IF EXISTS maasto2kuvionreuna_pkey;
ALTER TABLE IF EXISTS ONLY public.maaaineksenottoalue DROP CONSTRAINT IF EXISTS maaaineksenottoalue_pkey;
ALTER TABLE IF EXISTS ONLY public.luonnonsuojelualue DROP CONSTRAINT IF EXISTS luonnonsuojelualue_pkey;
ALTER TABLE IF EXISTS ONLY public.luiska DROP CONSTRAINT IF EXISTS luiska_pkey;
ALTER TABLE IF EXISTS ONLY public.lahde DROP CONSTRAINT IF EXISTS lahde_pkey;
ALTER TABLE IF EXISTS ONLY public.kunta DROP CONSTRAINT IF EXISTS kunta_pkey;
ALTER TABLE IF EXISTS ONLY public.kunnanhallintoraja DROP CONSTRAINT IF EXISTS kunnanhallintoraja_pkey;
ALTER TABLE IF EXISTS ONLY public.koski DROP CONSTRAINT IF EXISTS koski_pkey;
ALTER TABLE IF EXISTS ONLY public.korkeuskiintopiste DROP CONSTRAINT IF EXISTS korkeuskiintopiste_pkey;
ALTER TABLE IF EXISTS ONLY public.korkeuskayrankorkeusarvo DROP CONSTRAINT IF EXISTS korkeuskayrankorkeusarvo_pkey;
ALTER TABLE IF EXISTS ONLY public.korkeuskayra DROP CONSTRAINT IF EXISTS korkeuskayra_pkey;
ALTER TABLE IF EXISTS ONLY public.kolmiopiste DROP CONSTRAINT IF EXISTS kolmiopiste_pkey;
ALTER TABLE IF EXISTS ONLY public.kivikko DROP CONSTRAINT IF EXISTS kivikko_pkey;
ALTER TABLE IF EXISTS ONLY public.kivi DROP CONSTRAINT IF EXISTS kivi_pkey;
ALTER TABLE IF EXISTS ONLY public.kellotapuli DROP CONSTRAINT IF EXISTS kellotapuli_pkey;
ALTER TABLE IF EXISTS ONLY public.karttasymboli DROP CONSTRAINT IF EXISTS karttasymboli_pkey;
ALTER TABLE IF EXISTS ONLY public.kansallispuisto DROP CONSTRAINT IF EXISTS kansallispuisto_pkey;
ALTER TABLE IF EXISTS ONLY public.kalliosymboli DROP CONSTRAINT IF EXISTS kalliosymboli_pkey;
ALTER TABLE IF EXISTS ONLY public.kallioalue DROP CONSTRAINT IF EXISTS kallioalue_pkey;
ALTER TABLE IF EXISTS ONLY public.kaislikko DROP CONSTRAINT IF EXISTS kaislikko_pkey;
ALTER TABLE IF EXISTS ONLY public.jyrkanne DROP CONSTRAINT IF EXISTS jyrkanne_pkey;
ALTER TABLE IF EXISTS ONLY public.jarvi DROP CONSTRAINT IF EXISTS jarvi_pkey;
ALTER TABLE IF EXISTS ONLY public.hautausmaa DROP CONSTRAINT IF EXISTS hautausmaa_pkey;
ALTER TABLE IF EXISTS ONLY public.harvalouhikko DROP CONSTRAINT IF EXISTS harvalouhikko_pkey;
ALTER TABLE IF EXISTS ONLY public.autoliikennealue DROP CONSTRAINT IF EXISTS autoliikennealue_pkey;
ALTER TABLE IF EXISTS ONLY public.allas DROP CONSTRAINT IF EXISTS allas_pkey;
ALTER TABLE IF EXISTS public.virtavesikapea ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.virtavesialue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.virtausnuoli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.viettoviiva ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.vesikuoppa ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.vesikulkuvayla ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.vesikivikko ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.vesikivi ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.vedenpinnankorkeusluku ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.urheilujavirkistysalue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.tulentekopaikka ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.tieviiva ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.tiesymboli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.tienroteksti ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.syvyyspiste ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.syvyyskayransyvyysarvo ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.syvyyskayra ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.suurjannitelinjanpylvas ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.suojelualueenreunaviiva ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.suo ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.soistuma ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.selite ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.sahkolinjansymboli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.sahkolinja ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.rauhoitettukohde ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.rakennusreunaviiva ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.rakennus ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.rakennelma ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.pato ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.paikannimi ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.niitty ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.muuntaja ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.muuavoinalue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.metsamaankasvillisuus ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.matalikko ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.mastonkorkeus ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.masto ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.maatuvavesialue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.maatalousmaa ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.maastokuvionreuna ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.maasto2kuvionreuna ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.maaaineksenottoalue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.luonnonsuojelualue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.luiska ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.lahde ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kunta ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kunnanhallintoraja ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.koski ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.korkeuskiintopiste ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.korkeuskayrankorkeusarvo ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.korkeuskayra ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kolmiopiste ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kivikko ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kivi ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kellotapuli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.karttasymboli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kansallispuisto ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kalliosymboli ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kallioalue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.kaislikko ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.jyrkanne ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.jarvi ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.hautausmaa ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.harvalouhikko ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.autoliikennealue ALTER COLUMN ogc_fid DROP DEFAULT;
ALTER TABLE IF EXISTS public.allas ALTER COLUMN ogc_fid DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.virtavesikapea_ogc_fid_seq;
DROP TABLE IF EXISTS public.virtavesikapea;
DROP SEQUENCE IF EXISTS public.virtavesialue_ogc_fid_seq;
DROP TABLE IF EXISTS public.virtavesialue;
DROP SEQUENCE IF EXISTS public.virtausnuoli_ogc_fid_seq;
DROP TABLE IF EXISTS public.virtausnuoli;
DROP SEQUENCE IF EXISTS public.viettoviiva_ogc_fid_seq;
DROP TABLE IF EXISTS public.viettoviiva;
DROP SEQUENCE IF EXISTS public.vesikuoppa_ogc_fid_seq;
DROP TABLE IF EXISTS public.vesikuoppa;
DROP SEQUENCE IF EXISTS public.vesikulkuvayla_ogc_fid_seq;
DROP TABLE IF EXISTS public.vesikulkuvayla;
DROP SEQUENCE IF EXISTS public.vesikivikko_ogc_fid_seq;
DROP TABLE IF EXISTS public.vesikivikko;
DROP SEQUENCE IF EXISTS public.vesikivi_ogc_fid_seq;
DROP TABLE IF EXISTS public.vesikivi;
DROP SEQUENCE IF EXISTS public.vedenpinnankorkeusluku_ogc_fid_seq;
DROP TABLE IF EXISTS public.vedenpinnankorkeusluku;
DROP SEQUENCE IF EXISTS public.urheilujavirkistysalue_ogc_fid_seq;
DROP TABLE IF EXISTS public.urheilujavirkistysalue;
DROP SEQUENCE IF EXISTS public.tulentekopaikka_ogc_fid_seq;
DROP TABLE IF EXISTS public.tulentekopaikka;
DROP SEQUENCE IF EXISTS public.tieviiva_ogc_fid_seq;
DROP TABLE IF EXISTS public.tieviiva;
DROP SEQUENCE IF EXISTS public.tiesymboli_ogc_fid_seq;
DROP TABLE IF EXISTS public.tiesymboli;
DROP SEQUENCE IF EXISTS public.tienroteksti_ogc_fid_seq;
DROP TABLE IF EXISTS public.tienroteksti;
DROP SEQUENCE IF EXISTS public.syvyyspiste_ogc_fid_seq;
DROP TABLE IF EXISTS public.syvyyspiste;
DROP SEQUENCE IF EXISTS public.syvyyskayransyvyysarvo_ogc_fid_seq;
DROP TABLE IF EXISTS public.syvyyskayransyvyysarvo;
DROP SEQUENCE IF EXISTS public.syvyyskayra_ogc_fid_seq;
DROP TABLE IF EXISTS public.syvyyskayra;
DROP SEQUENCE IF EXISTS public.suurjannitelinjanpylvas_ogc_fid_seq;
DROP TABLE IF EXISTS public.suurjannitelinjanpylvas;
DROP SEQUENCE IF EXISTS public.suojelualueenreunaviiva_ogc_fid_seq;
DROP TABLE IF EXISTS public.suojelualueenreunaviiva;
DROP SEQUENCE IF EXISTS public.suo_ogc_fid_seq;
DROP TABLE IF EXISTS public.suo;
DROP SEQUENCE IF EXISTS public.soistuma_ogc_fid_seq;
DROP TABLE IF EXISTS public.soistuma;
DROP SEQUENCE IF EXISTS public.selite_ogc_fid_seq;
DROP TABLE IF EXISTS public.selite;
DROP SEQUENCE IF EXISTS public.sahkolinjansymboli_ogc_fid_seq;
DROP TABLE IF EXISTS public.sahkolinjansymboli;
DROP SEQUENCE IF EXISTS public.sahkolinja_ogc_fid_seq;
DROP TABLE IF EXISTS public.sahkolinja;
DROP SEQUENCE IF EXISTS public.rauhoitettukohde_ogc_fid_seq;
DROP TABLE IF EXISTS public.rauhoitettukohde;
DROP SEQUENCE IF EXISTS public.rakennusreunaviiva_ogc_fid_seq;
DROP TABLE IF EXISTS public.rakennusreunaviiva;
DROP SEQUENCE IF EXISTS public.rakennus_ogc_fid_seq;
DROP TABLE IF EXISTS public.rakennus;
DROP SEQUENCE IF EXISTS public.rakennelma_ogc_fid_seq;
DROP TABLE IF EXISTS public.rakennelma;
DROP SEQUENCE IF EXISTS public.pato_ogc_fid_seq;
DROP TABLE IF EXISTS public.pato;
DROP SEQUENCE IF EXISTS public.paikannimi_ogc_fid_seq;
DROP TABLE IF EXISTS public.paikannimi;
DROP SEQUENCE IF EXISTS public.niitty_ogc_fid_seq;
DROP TABLE IF EXISTS public.niitty;
DROP SEQUENCE IF EXISTS public.muuntaja_ogc_fid_seq;
DROP TABLE IF EXISTS public.muuntaja;
DROP SEQUENCE IF EXISTS public.muuavoinalue_ogc_fid_seq;
DROP TABLE IF EXISTS public.muuavoinalue;
DROP SEQUENCE IF EXISTS public.metsamaankasvillisuus_ogc_fid_seq;
DROP TABLE IF EXISTS public.metsamaankasvillisuus;
DROP SEQUENCE IF EXISTS public.matalikko_ogc_fid_seq;
DROP TABLE IF EXISTS public.matalikko;
DROP SEQUENCE IF EXISTS public.mastonkorkeus_ogc_fid_seq;
DROP TABLE IF EXISTS public.mastonkorkeus;
DROP SEQUENCE IF EXISTS public.masto_ogc_fid_seq;
DROP TABLE IF EXISTS public.masto;
DROP SEQUENCE IF EXISTS public.maatuvavesialue_ogc_fid_seq;
DROP TABLE IF EXISTS public.maatuvavesialue;
DROP SEQUENCE IF EXISTS public.maatalousmaa_ogc_fid_seq;
DROP TABLE IF EXISTS public.maatalousmaa;
DROP SEQUENCE IF EXISTS public.maastokuvionreuna_ogc_fid_seq;
DROP TABLE IF EXISTS public.maastokuvionreuna;
DROP SEQUENCE IF EXISTS public.maasto2kuvionreuna_ogc_fid_seq;
DROP TABLE IF EXISTS public.maasto2kuvionreuna;
DROP SEQUENCE IF EXISTS public.maaaineksenottoalue_ogc_fid_seq;
DROP TABLE IF EXISTS public.maaaineksenottoalue;
DROP SEQUENCE IF EXISTS public.luonnonsuojelualue_ogc_fid_seq;
DROP TABLE IF EXISTS public.luonnonsuojelualue;
DROP SEQUENCE IF EXISTS public.luiska_ogc_fid_seq;
DROP TABLE IF EXISTS public.luiska;
DROP SEQUENCE IF EXISTS public.lahde_ogc_fid_seq;
DROP TABLE IF EXISTS public.lahde;
DROP SEQUENCE IF EXISTS public.kunta_ogc_fid_seq;
DROP TABLE IF EXISTS public.kunta;
DROP SEQUENCE IF EXISTS public.kunnanhallintoraja_ogc_fid_seq;
DROP TABLE IF EXISTS public.kunnanhallintoraja;
DROP SEQUENCE IF EXISTS public.koski_ogc_fid_seq;
DROP TABLE IF EXISTS public.koski;
DROP SEQUENCE IF EXISTS public.korkeuskiintopiste_ogc_fid_seq;
DROP TABLE IF EXISTS public.korkeuskiintopiste;
DROP SEQUENCE IF EXISTS public.korkeuskayrankorkeusarvo_ogc_fid_seq;
DROP TABLE IF EXISTS public.korkeuskayrankorkeusarvo;
DROP SEQUENCE IF EXISTS public.korkeuskayra_ogc_fid_seq;
DROP TABLE IF EXISTS public.korkeuskayra;
DROP SEQUENCE IF EXISTS public.kolmiopiste_ogc_fid_seq;
DROP TABLE IF EXISTS public.kolmiopiste;
DROP SEQUENCE IF EXISTS public.kivikko_ogc_fid_seq;
DROP TABLE IF EXISTS public.kivikko;
DROP SEQUENCE IF EXISTS public.kivi_ogc_fid_seq;
DROP TABLE IF EXISTS public.kivi;
DROP SEQUENCE IF EXISTS public.kellotapuli_ogc_fid_seq;
DROP TABLE IF EXISTS public.kellotapuli;
DROP SEQUENCE IF EXISTS public.karttasymboli_ogc_fid_seq;
DROP TABLE IF EXISTS public.karttasymboli;
DROP SEQUENCE IF EXISTS public.kansallispuisto_ogc_fid_seq;
DROP TABLE IF EXISTS public.kansallispuisto;
DROP SEQUENCE IF EXISTS public.kalliosymboli_ogc_fid_seq;
DROP TABLE IF EXISTS public.kalliosymboli;
DROP SEQUENCE IF EXISTS public.kallioalue_ogc_fid_seq;
DROP TABLE IF EXISTS public.kallioalue;
DROP SEQUENCE IF EXISTS public.kaislikko_ogc_fid_seq;
DROP TABLE IF EXISTS public.kaislikko;
DROP SEQUENCE IF EXISTS public.jyrkanne_ogc_fid_seq;
DROP TABLE IF EXISTS public.jyrkanne;
DROP SEQUENCE IF EXISTS public.jarvi_ogc_fid_seq;
DROP TABLE IF EXISTS public.jarvi;
DROP SEQUENCE IF EXISTS public.hautausmaa_ogc_fid_seq;
DROP TABLE IF EXISTS public.hautausmaa;
DROP SEQUENCE IF EXISTS public.harvalouhikko_ogc_fid_seq;
DROP TABLE IF EXISTS public.harvalouhikko;
DROP SEQUENCE IF EXISTS public.autoliikennealue_ogc_fid_seq;
DROP TABLE IF EXISTS public.autoliikennealue;
DROP SEQUENCE IF EXISTS public.allas_ogc_fid_seq;
DROP TABLE IF EXISTS public.allas;
